"use client";

import { formatMoney } from "@infinity-radius/ui";
import { presentCollectionStatus } from "@/lib/collections/status";
import { formatDateTime, orDash } from "@/lib/collections/format";
import type { TransactionRead } from "@/lib/api-types";
import { CollectionStatusBadge } from "./collection-status-badge";

export interface CollectionDetailDrawerProps {
  transaction: TransactionRead | null;
  onClose: () => void;
}

/**
 * Read-only detail panel.
 *
 * The four identifiers are labelled distinctly on purpose — calling any of
 * them just "Transaction ID" is what made a real production incident hard
 * to reason about. Each one has a different origin and a different use,
 * and support needs to be able to tell them apart at a glance.
 */
export function CollectionDetailDrawer({ transaction, onClose }: CollectionDetailDrawerProps) {
  if (!transaction) return null;

  const presentation = presentCollectionStatus(transaction.status);

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 sm:items-center sm:p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="collection-detail-title"
    >
      <div className="bg-surface-container-low max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-t-2xl p-5 sm:rounded-2xl sm:p-6">
        <div className="mb-4 flex items-start justify-between gap-4">
          <h2 id="collection-detail-title" className="text-on-surface text-lg font-semibold">
            Payment details
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="text-on-surface-variant hover:text-on-surface text-sm"
            aria-label="Close"
          >
            Close
          </button>
        </div>

        <div className="mb-4 flex items-center justify-between gap-3">
          <span className="text-on-surface text-2xl font-semibold">
            {formatMoney(transaction.amount, transaction.currency) ??
              `${transaction.currency} ${transaction.amount}`}
          </span>
          <CollectionStatusBadge status={transaction.status} />
        </div>

        <p
          className={
            presentation.tone === "success"
              ? "text-success mb-5 text-sm"
              : presentation.tone === "attention" || presentation.tone === "unknown"
                ? "text-warning mb-5 text-sm"
                : "text-on-surface-variant mb-5 text-sm"
          }
        >
          {presentation.message}
        </p>

        <Section title="Payment">
          <Row label="Customer" value={orDash(transaction.payer_phone_masked)} mono />
          <Row label="Channel" value={orDash(transaction.channel)} />
          <Row label="Currency" value={transaction.currency} />
          {/* Provider status word only (e.g. "COMPLETED"/"PENDING") — the
              API never returns a raw provider error or stack trace here. */}
          <Row label="Provider status" value={orDash(transaction.provider_message)} />
        </Section>

        <Section title="References">
          <Row label="Infinity Radius Order ID" value={transaction.reference} mono />
          <Row
            label="Local Request ID"
            value={orDash(transaction.collection_transid)}
            mono
            hint="Generated by Infinity Radius for the payment request."
          />
          <Row
            label="Mobile Money Reference"
            value={orDash(transaction.provider_reference)}
            mono
            hint="The payment channel's own receipt, available once completed."
          />
          <Row label="Internal ID" value={transaction.id} mono />
        </Section>

        <Section title="Timeline">
          <Row label="Created" value={formatDateTime(transaction.created_at)} />
          <Row label="Request sent" value={formatDateTime(transaction.stk_requested_at)} />
          <Row label="Completed" value={formatDateTime(transaction.completed_at)} />
          <Row label="Ended" value={formatDateTime(transaction.failed_at)} />
          <Row label="Last updated" value={formatDateTime(transaction.updated_at)} />
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-5">
      <h3 className="text-on-surface-variant mb-2 text-[0.6875rem] font-semibold uppercase tracking-wider">
        {title}
      </h3>
      <dl className="flex flex-col gap-2">{children}</dl>
    </section>
  );
}

function Row({
  label,
  value,
  mono,
  hint,
}: {
  label: string;
  value: string;
  mono?: boolean;
  hint?: string;
}) {
  return (
    <div className="flex flex-col gap-0.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4">
      <dt className="text-on-surface-variant shrink-0 text-sm">{label}</dt>
      <dd
        className={
          mono
            ? "text-on-surface break-all font-mono text-xs sm:text-right"
            : "text-on-surface text-sm sm:text-right"
        }
      >
        {value}
        {hint && <span className="text-on-surface-variant block text-xs font-sans">{hint}</span>}
      </dd>
    </div>
  );
}
